from typing import List

from Level import Level

class LevelManager:
    def __init__(self):
        self.levels: List[Level]
        self.current_level: Level

    def add_level(self, level: Level) -> None: ...
    def get_current_level(self) -> Level: ...
    def get_current_level_name(self) -> str: ...
    def set_current_level(self, index: int) -> None: ...

    def load_level_files(self, folder: str) -> None: ...